# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='categoty',
            new_name='game_category',
        ),
    ]
