# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField()),
                ('y_value', models.FloatField()),
                ('op', models.CharField(choices=[('SUM', '+'), ('SUB', '-'), ('MUL', '*'), ('DIV', '/'), ('POW', '^')], default='SUM', max_length=1)),
            ],
        ),
    ]
