# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20170831_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='operation',
            new_name='op',
        ),
    ]
