# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20170831_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='operator',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='operation',
            name='op',
            field=models.CharField(blank=True, choices=[('SUM', '+'), ('SUB', '-'), ('MUL', '*'), ('DIV', '/'), ('POW', '^')], max_length=3),
        ),
    ]
